modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="gtcemcaddon"
version="1.0.0"
displayName="GTCe Modern EMC Addon"
description="Auto EMC values for GregTech CEu Modern via ProjectE datapack"

[[dependencies.gtcemcaddon]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gtcemcaddon]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"

[[dependencies.gtcemcaddon]]
    modId="projecte"
    mandatory=true
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.gtcemcaddon]]
    modId="gtceu"
    mandatory=true
    versionRange="[1.0,)"
    ordering="AFTER"
    side="BOTH"
